# docker buildx build --progress=plain -f Docker/Dockerfile-vis -t vis-test . 

# ----------------------------------------------------------------------
# JupyterLab Notebook for analyzing E3SM-ELM land model output
# with Google Earth Engine and GEEmap
# ----------------------------------------------------------------------

FROM quay.io/jupyter/scipy-notebook:lab-4.4.9

# install Python packages you often use
RUN set -ex \
   && conda install --quiet --yes \
   # choose the Python packages you need
   'matplotlib' \
   'plotly' \
   'folium' \
   'dask' \
   'pandas' \
   'xarray' \
   'geopandas' \
   'ipyleaflet' \
   && conda clean --all -f -y \
   && conda install --quiet --yes -c conda-forge \
   'nc-time-axis' \
   'netCDF4' \
   && conda clean --all -f -y \
   && mamba install --quiet --yes -c conda-forge \
   'earthengine-api' \
   'geemap' \
   'pygis' \
   'ilamb' \
   && mamba clean --all -f -y \
   && rm -rf "/home/${NB_USER}/.cache/yarn" \
   && rm -rf "/home/${NB_USER}/.node-gyp" \
   && fix-permissions "${CONDA_DIR}" \
   && fix-permissions "/home/${NB_USER}"

# Make local directories to use with plotting of ELM output
RUN mkdir "/home/${NB_USER}/scripts" \
   && mkdir "/home/${NB_USER}/inputdata" \
   && mkdir "/home/${NB_USER}/output" \
   && fix-permissions "/home/${NB_USER}/scripts" \
   && fix-permissions "/home/${NB_USER}/inputdata" \
   && fix-permissions "/home/${NB_USER}/output" \
   && fix-permissions "/home/${NB_USER}"

# Setup default user, when enter docker container
USER ${NB_UID}
WORKDIR "${HOME}"

# Download, install dapper
RUN git clone https://github.com/ngee-arctic/dapper \
  && cd dapper \
  && pip install -e .

RUN \
		python -c "import ILAMB; print(ILAMB.__version__)" \
		&& python -c "import dapper; print(dapper.__version__)"

#EOF
