# The image for building and serving the sphinx docs.
# Build with: 
#     docker build --tag docbuilder -o type=local,dest=build -f Docker/Dockerfile-docs .
FROM sphinxdoc/sphinx AS docbuilder

COPY docs/requirements.txt /tmp/requirements.txt

RUN pip install -r /tmp/requirements.txt

WORKDIR /docs

COPY docs /docs

RUN make html

FROM scratch

COPY --from=docbuilder /docs/build/html /
