if (COMP_NAME STREQUAL gptl)
  string(APPEND CPPDEFS " -DHAVE_VPRINTF -DHAVE_GETTIMEOFDAY -DHAVE_BACKTRACE")
endif()
set(APPEND FFLAGS " -fallow-argument-mismatch -fallow-invalid-boz")
if (NOT DEBUG)
  string(APPEND FFLAGS " -fno-unsafe-math-optimizations")
endif()
if (DEBUG)
  string(APPEND FFLAGS " -g -fbacktrace -fbounds-check -ffpe-trap=invalid,zero,overflow")
endif()
string(APPEND CXX_LIBS " -lstdc++")
string(APPEND SLIBS " -L$ENV{HDF5_ROOT}/lib -lhdf5_fortran -lhdf5 -lhdf5_hl -lhdf5_hl_fortran")
string(APPEND SLIBS " -L$ENV{NETCDF_PATH}/lib/ -lnetcdff -lnetcdf -lcurl -lblas -llapack")
set(NETCDF_PATH "$ENV{NETCDF_PATH}")
set(NETCDF_DIR "$ENV{NETCDF_PATH}")

# set some compiler options:
set(CMAKE_C_COMPILER /usr/local/bin/mpicc CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER /usr/local/bin/mpicxx CACHE FILEPATH "")
set(CMAKE_Fortran_COMPILER /usr/local/bin/mpifort CACHE FILEPATH "")
set(CMAKE_IGNORE_PREFIX_PATH "/opt/conda" CACHE PATH "")
set(CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH OFF CACHE BOOL "")
set(CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH ON CACHE BOOL "")
