name: "Sphinx: Render docs"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare for build
        run: mkdir -p build

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Docker/Dockerfile-docs
          push: false
          outputs: type=local,dest=build


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
